// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctqtwrybwsilxfpnmpzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0cXR3cnlid3NpbHhmcG5tcHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjM5ODAsImV4cCI6MjA2OTYzOTk4MH0.w04KQz2IM8dUoye_v36uiMZTYmuZIibm7PlaT6cFSWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});